from flask import Flask, render_template, request, redirect, url_for, session, flash, send_from_directory
from werkzeug.security import generate_password_hash, check_password_hash
from pathlib import Path
import sqlite3
import os

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    psycopg = None

BASE_DIR = Path(__file__).resolve().parent
SQLITE_PATH = BASE_DIR / "site.db"
DATABASE_URL = os.environ.get("DATABASE_URL")

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "trocar-esta-chave-em-producao")


def using_postgres():
    return bool(DATABASE_URL)


def get_db():
    if using_postgres():
        return psycopg.connect(
            DATABASE_URL,
            row_factory=dict_row
        )

    conn = sqlite3.connect(SQLITE_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def query_one(sql_pg, sql_sqlite=None, params=()):
    con = get_db()

    try:
        sql = sql_pg if using_postgres() else (sql_sqlite or sql_pg)
        cur = con.execute(sql, params)
        return cur.fetchone()
    finally:
        con.close()


def query_all(sql_pg, sql_sqlite=None, params=()):
    con = get_db()

    try:
        sql = sql_pg if using_postgres() else (sql_sqlite or sql_pg)
        cur = con.execute(sql, params)
        return cur.fetchall()
    finally:
        con.close()


def init_db():
    con = get_db()

    try:
        if using_postgres():

            con.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    email TEXT UNIQUE NOT NULL,
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL DEFAULT 'student'
                )
            """)

            con.execute("""
                CREATE TABLE IF NOT EXISTS products (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title TEXT NOT NULL,
                    slug TEXT UNIQUE NOT NULL,
                    product_type TEXT NOT NULL DEFAULT 'ebook',
                    description TEXT,
                    price_cents INTEGER NOT NULL DEFAULT 0,
                    cover_file TEXT,
                    digital_file TEXT,
                    active INTEGER NOT NULL DEFAULT 1
                )
            """)

            con.execute("""
                CREATE TABLE IF NOT EXISTS courses (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title TEXT NOT NULL,
                    slug TEXT UNIQUE NOT NULL,
                    description TEXT,
                    price_cents INTEGER NOT NULL DEFAULT 0,
                    active INTEGER NOT NULL DEFAULT 0
                )
            """)

            con.execute("""
                CREATE TABLE IF NOT EXISTS entitlements (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id INTEGER NOT NULL REFERENCES users(id),
                    product_id INTEGER REFERENCES products(id),
                    course_id INTEGER REFERENCES courses(id)
                )
            """)

            con.execute("""
                INSERT INTO products (
                    title,
                    slug,
                    product_type,
                    description,
                    price_cents,
                    cover_file,
                    digital_file,
                    active
                )
                VALUES (
                    %s, %s, %s, %s, %s, %s, %s, %s
                )
                ON CONFLICT (slug) DO NOTHING
            """, (
                "Massas & Risotos",
                "massas-risotos",
                "ebook",
                "Técnicas, receitas e conhecimento prático para quem quer cozinhar melhor e compreender os processos por trás de cada preparo.",
                990,
                "capa-massas-risotos.PNG",
                "ebook-massas-daniel-costa.pdf",
                1
            ))

        else:

            con.executescript("""
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL,
                    email TEXT UNIQUE NOT NULL,
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL DEFAULT 'student'
                );

                CREATE TABLE IF NOT EXISTS products (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title TEXT NOT NULL,
                    slug TEXT UNIQUE NOT NULL,
                    product_type TEXT NOT NULL DEFAULT 'ebook',
                    description TEXT,
                    price_cents INTEGER NOT NULL DEFAULT 0,
                    cover_file TEXT,
                    digital_file TEXT,
                    active INTEGER NOT NULL DEFAULT 1
                );

                CREATE TABLE IF NOT EXISTS courses (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title TEXT NOT NULL,
                    slug TEXT UNIQUE NOT NULL,
                    description TEXT,
                    price_cents INTEGER NOT NULL DEFAULT 0,
                    active INTEGER NOT NULL DEFAULT 0
                );

                CREATE TABLE IF NOT EXISTS entitlements (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL,
                    product_id INTEGER,
                    course_id INTEGER
                );
            """)

            con.execute("""
                INSERT OR IGNORE INTO products (
                    title,
                    slug,
                    product_type,
                    description,
                    price_cents,
                    cover_file,
                    digital_file,
                    active
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                "Massas & Risotos",
                "massas-risotos",
                "ebook",
                "Técnicas, receitas e conhecimento prático para quem quer cozinhar melhor e compreender os processos por trás de cada preparo.",
                990,
                "capa-massas-risotos.PNG",
                "ebook-massas-daniel-costa.pdf",
                1
            ))

        con.commit()

    finally:
        con.close()


def current_user():
    user_id = session.get("user_id")

    if not user_id:
        return None

    if using_postgres():
        return query_one(
            "SELECT * FROM users WHERE id = %s",
            params=(user_id,)
        )

    return query_one(
        "",
        "SELECT * FROM users WHERE id = ?",
        (user_id,)
    )


def money(cents):
    return (
        f"R$ {cents / 100:,.2f}"
        .replace(",", "X")
        .replace(".", ",")
        .replace("X", ".")
    )


app.jinja_env.filters["money"] = money


@app.route("/")
def home():
    if using_postgres():
        products = query_all(
            "SELECT * FROM products WHERE active = 1 ORDER BY id DESC"
        )
    else:
        products = query_all(
            "",
            "SELECT * FROM products WHERE active = 1 ORDER BY id DESC"
        )

    return render_template(
        "index.html",
        products=products,
        user=current_user()
    )


@app.route("/produto/<slug>")
def product(slug):

    if using_postgres():
        product_data = query_one(
            "SELECT * FROM products WHERE slug = %s AND active = 1",
            params=(slug,)
        )
    else:
        product_data = query_one(
            "",
            "SELECT * FROM products WHERE slug = ? AND active = 1",
            (slug,)
        )

    if not product_data:
        return "Produto não encontrado", 404

    return render_template(
        "product.html",
        product=product_data,
        user=current_user()
    )


@app.route("/cadastro", methods=["GET", "POST"])
def register():

    if request.method == "POST":

        name = request.form["name"].strip()
        email = request.form["email"].strip().lower()
        password = request.form["password"]

        con = get_db()

        try:
            password_hash = generate_password_hash(password)

            if using_postgres():

                cur = con.execute("""
                    INSERT INTO users (
                        name,
                        email,
                        password_hash,
                        role
                    )
                    VALUES (%s, %s, %s, %s)
                    RETURNING id
                """, (
                    name,
                    email,
                    password_hash,
                    "student"
                ))

                new_user = cur.fetchone()
                user_id = new_user["id"]

            else:

                cur = con.execute("""
                    INSERT INTO users (
                        name,
                        email,
                        password_hash,
                        role
                    )
                    VALUES (?, ?, ?, ?)
                """, (
                    name,
                    email,
                    password_hash,
                    "student"
                ))

                user_id = cur.lastrowid

            con.commit()

            session["user_id"] = user_id

            return redirect(url_for("library"))

        except Exception as e:

            con.rollback()

            if "unique" in str(e).lower() or "duplicate" in str(e).lower():
                flash("Este e-mail já está cadastrado.")
            else:
                print("Erro no cadastro:", e)
                flash("Não foi possível criar a conta.")

        finally:
            con.close()

    return render_template(
        "register.html",
        user=current_user()
    )


@app.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":

        email = request.form["email"].strip().lower()
        password = request.form["password"]

        if using_postgres():

            user = query_one(
                "SELECT * FROM users WHERE email = %s",
                params=(email,)
            )

        else:

            user = query_one(
                "",
                "SELECT * FROM users WHERE email = ?",
                (email,)
            )

        if user and check_password_hash(
            user["password_hash"],
            password
        ):

            session["user_id"] = user["id"]

            if user["role"] == "admin":
                return redirect(url_for("admin"))

            return redirect(url_for("library"))

        flash("E-mail ou senha inválidos.")

    return render_template(
        "login.html",
        user=current_user()
    )


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("home"))


@app.route("/biblioteca")
def library():

    user = current_user()

    if not user:
        return redirect(url_for("login"))

    if using_postgres():

        products = query_all(
            "SELECT * FROM products WHERE active = 1 ORDER BY id DESC"
        )

    else:

        products = query_all(
            "",
            "SELECT * FROM products WHERE active = 1 ORDER BY id DESC"
        )

    return render_template(
        "library.html",
        products=products,
        user=user
    )


@app.route("/ler/<slug>")
def reader(slug):

    user = current_user()

    if not user:
        return redirect(url_for("login"))

    if using_postgres():

        product_data = query_one(
            "SELECT * FROM products WHERE slug = %s",
            params=(slug,)
        )

    else:

        product_data = query_one(
            "",
            "SELECT * FROM products WHERE slug = ?",
            (slug,)
        )

    if not product_data:
        return "Produto não encontrado", 404

    return render_template(
        "reader.html",
        product=product_data,
        user=user
    )


@app.route("/arquivo/<path:filename>")
def file(filename):
    return send_from_directory(BASE_DIR, filename)


def is_admin():
    user = current_user()
    return bool(user and user["role"] == "admin")


@app.route("/admin")
def admin():

    if not is_admin():
        return redirect(url_for("login"))

    if using_postgres():

        products = query_all(
            "SELECT * FROM products ORDER BY id DESC"
        )

        courses = query_all(
            "SELECT * FROM courses ORDER BY id DESC"
        )

    else:

        products = query_all(
            "",
            "SELECT * FROM products ORDER BY id DESC"
        )

        courses = query_all(
            "",
            "SELECT * FROM courses ORDER BY id DESC"
        )

    return render_template(
        "admin.html",
        products=products,
        courses=courses,
        user=current_user()
    )


init_db()


if __name__ == "__main__":
    app.run(debug=True)
